---
- name: Playbook buat install IPA client dengan username dan password
- hosts: ipaclients
  become: true
  vars_files:
  - hosts
  
  tasks:
  - name: "Periksa EPEL repo"
    stat: path={{ epel_repo_url }}
    register: epel_repofile_result
    
  - name: "Install EPEL repo"
    yum:
     name: "{{ epel_repo_url }}"
     state: present
    register: result
    until: 'result.rc == 0'
    retries: 3
    delay: 10
    when: not epel_repofile_result.stat.exists
   
  - name: "Import EPEL GPG key."
    rpm_key:
      key: "{{ epel_gpg_key }}"
      state: present
    when: not epel_repofile_result.stat.exists
    ignore_errors: "{{ ansible_check_mode }}"

  - name: "Update yum"
    yum:
      name: '*'
      state: latest
      
  - name: "Install IPA Client"
    package:
      name: ipa-client
      state: present

  - name: "Configure  IPA client"
    ipaclient:
      state: present
      domain: "{{ ipaclient_domain }}"
      realm: "{{ ipaclient_realm }}"
      principal: "{{ ipaclient_principal }}"
      password: "{{ ipaclient_password }}"
      extra_args: "{{ ipaclient_extraargs }}"